### ISSUE TITLE
Замечания по лабораторной работе №5

### ISSUE THREAD

**Issue by kerim-ar** [eCREATORx/web-development#1]
- [x] Зачем лишняя вложенность для картинки (тег div)?
https://github.com/eCREATORx/web-development/blob/6f3a64932fe54a6e7219632b1114f2907bd25339/lw5/index.html#L11

- [x] Лучше давать более осмысленные имена классам для элементов, например `sidebar_title`
https://github.com/eCREATORx/web-development/blob/6f3a64932fe54a6e7219632b1114f2907bd25339/lw5/index.html#L22
Если вы тег p замените на span, то вам придется менять названия класса в html и css

- [ ] Вы не подгружаете шрифт Georgia
https://github.com/eCREATORx/web-development/blob/6f3a64932fe54a6e7219632b1114f2907bd25339/lw5/css/style.css#L35

- [x] Для сдачи 5.2 нужно сверстать обновленный дизайн страницы, которого пока у вас нет.
Посмотрите еще раз задание лабораторной работы №5

**Comment by eCREATORx** [comment]
Я исправила замечания, кроме подгрузки шрифта Georgia, его невозможно добавить с сайта Google Fonts. Добавила вторую часть задания с обновлённым дизайном.

**Comment by kerim-ar** [comment]
- [ ] Сравните еще раз вашу страницу с дизайном. Сейчас как минимум съехала кнопка

- [ ] Прочитайте еще раз соглашение о кодировании CSS
https://drive.google.com/file/d/0BwVxw_xrDzIKampPXy1rRndzSk0/view
1) У вас используются в перемешку табы и пробелы
2) После 0 единицы измерения не ставятся

- [ ] У вас используется position: sticky, но залипания нет. Зачем так?
https://github.com/eCREATORx/web-development/blob/7cc2711144f759f9e40366d8a8a3e4040908be40/lw5/task2/css/style.css#L22

- [ ] Почему у вас разного цвета иконки в верхней панели?

- [ ] Не нужно использовать position: absolute
https://github.com/eCREATORx/web-development/blob/7cc2711144f759f9e40366d8a8a3e4040908be40/lw5/task2/css/style.css#L90

**Comment by eCREATORx** [comment]
Исправила ошибки, сократила некоторые записи в CSS, добавила изменение иконки в меню навигации при наведении.

**Comment by kerim-ar** [comment]
- [ ] Появился горизонтальный скролл на странице, его не должно быть

- [ ] Позиция иконок в верхнем меню немного не такая как в дизайне

- [ ] Нужно давать более осмысленные имена классам, а не `icon_lists1`
https://github.com/eCREATORx/web-development/blob/85e797e5652d353d83661ea2ffa99d0e4bf13551/lw5/task2/index.html#L12

- [ ] У вас одни и те-же стили дублируются несколько раз
https://github.com/eCREATORx/web-development/blob/85e797e5652d353d83661ea2ffa99d0e4bf13551/lw5/task2/css/style.css#L56
Для `a img.icon_lists1`, `a img.icon_lists2` и `a img.icon_lists3`. Нужно избавиться от дублирования стилей

- [ ] Если вы хотите растянуть контейнер на всю ширину, то нужно использовать проценты для ширины
https://github.com/eCREATORx/web-development/blob/85e797e5652d353d83661ea2ffa99d0e4bf13551/lw5/task2/css/style.css#L103
У разных пользователей может быть разный размер экрана

**Comment by kerim-ar** [comment]
- [ ] Проверьте иконки для наведенного состояния в "Мое хобби" и "Любимые фильмы" в верхней панели. Они выглядят немного по-другому

**Comment by eCREATORx** [comment]
Кажется, всё исправила, кроме позиции иконок в верхнем меню. Я попробовала их двигать с помощью padding, но они двигаются вместе с текстом, так что всё равно что-то будет отличаться.
